// Customer screen actions
export const SEARCH_CUSTOMERS_SUCCESS = 'SEARCH_CUSTOMERS_SUCCESS';
export const SEARCH_TEXT_CHANGED = 'SEARCH_TEXT_CHANGED';
export const CUSTOMER_SEARCH_BUTTON_CLICKED = 'CUSTOMER_SEARCH_BUTTON_CLICKED';

// Ajax actions
export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';