// Customer search screen actions
export const SEARCH_CUSTOMERS_SUCCESS = 'SEARCH_CUSTOMERS_SUCCESS';
export const SEARCH_TEXT_CHANGED = 'SEARCH_TEXT_CHANGED';
export const CUSTOMER_EDIT_BUTTON_CLICKED = 'CUSTOMER_EDIT_BUTTON_CLICKED';
export const CUSTOMER_SEARCH_TAB_CHANGED = 'CUSTOMER_SEARCH_TAB_CHANGED';
export const GET_RECENT_CUSTOMERS = 'GET_RECENT_CUSTOMERS';
export const CLEAR_RECENT_CUSTOMERS = 'CLEAR_RECENT_CUSTOMERS';

// Customer edit screen actions
export const GET_CUSTOMER_SUCCESS = 'GET_CUSTOMER_SUCCESS';
export const CLEAR_CUSTOMER = 'CLEAR_CUSTOMER';

// Order entry screen actions
export const ITEM_SEARCH_TEXT_CHANGED = 'ITEM_SEARCH_TEXT_CHANGED';
export const SEARCH_ITEMS_SUCCESS = 'SEARCH_ITEMS_SUCCESS';
export const ADD_ITEM_TO_ORDER = 'ADD_ITEM_TO_ORDER';
export const ITEM_QUANTITY_CHANGED = 'ITEM_QUANTITY_CHANGED';
export const PO_NUMBER_CHANGED = 'PO_NUMBER_CHANGED';
export const SHIPTO_ADDRESS_CHANGED = 'SHIPTO_ADDRESS_CHANGED';

// Ajax actions
export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';