// Customer screen actions
export const SEARCH_CUSTOMERS_SUCCESS = 'SEARCH_CUSTOMERS_SUCCESS';
export const SEARCH_TEXT_CHANGED = 'SEARCH_TEXT_CHANGED';
export const CUSTOMER_EDIT_BUTTON_CLICKED = 'CUSTOMER_EDIT_BUTTON_CLICKED';
export const CUSTOMER_SEARCH_TAB_CHANGED = 'CUSTOMER_SEARCH_TAB_CHANGED';
export const GET_RECENT_CUSTOMERS = 'GET_RECENT_CUSTOMERS';

// Ajax actions
export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';